Repository Part4-Team13/Delimood, pull requests merged in 2024-07, with the labels that each got.

#4 FE-48 ✨ Auth API 작업
  src/apis/auth.ts
  src/apis/user.ts
  src/hooks/authQuery.ts
  src/hooks/useUserQuery.ts
  src/schema/authSchema.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#3 FE-53 :sparkles: CSS 기초세팅
  global.css
  src/App.tsx
  src/assets/ico_X.svg
  src/assets/ico_arrow_down.svg
  src/assets/ico_arrow_down_gray.svg
  src/assets/ico_arrow_left.svg
  src/assets/ico_arrow_right.svg
  src/assets/ico_arrow_up.svg
  src/assets/ico_camera.svg
  src/assets/ico_external_link.svg
  src/assets/ico_face_angry.svg
  src/assets/ico_face_heart.svg
  src/assets/ico_face_sad.svg
  src/assets/ico_face_smiling.svg
  src/assets/ico_face_thinking.svg
  src/assets/ico_like.svg
  src/assets/ico_logo.svg
  src/assets/ico_more_arrow_down.svg
  src/assets/ico_more_vertical.svg
  src/assets/ico_search.svg
  src/assets/ico_share.svg
  src/assets/ico_user.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/assets/img_magnifier.png
  src/assets/img_paraph.png
  src/assets/img_paraph_small.png
  src/assets/img_pr_emotions.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_examples.png
  src/assets/img_pr_graph.png
  src/index.css
  src/main.tsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#5 FE-54 ✨ 라우터 설정
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/.empty
  src/pages/addepigram/index.tsx
  src/pages/epigrams/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/pages/signup/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#1 FE-50 ✨ EmotionLog API 작업
  src/apis/emotionLog.ts
  src/hooks/useEmotionLogQuery.ts
  src/schema/emotionLogSchema.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#7 FE-50 ✨ Comment API 작업
  src/apis/comment.ts
  src/hooks/useCommentQuery.ts
  src/schema/commentSchema.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#2 FE-49 ✨ Epigram 스키마 API 작업
  package-lock.json
  src/App.tsx
  src/apis/common.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
Labels: Priority: Medium :bookmark:, Type: Doc :memo:, Type: Feature :sparkles:

#9 FE-53 🐛 css 기초세팅 오타 및 버그 수정
  tailwind.config.js
Labels: Priority: Medium :bookmark:
