Repository Part4-Team13/Delimood, pull requests merged in 2024-08, with the labels that each got.

#10 FE-53 ✨ index.css 추가
  src/index.css
  src/main.tsx
Labels: Priority: Medium :bookmark:

#11 FE-52 ♻️ Comment API 쿼리 키 팩토리 적용
  src/apis/comment.ts
  src/apis/queries.ts
  src/hooks/useCommentQuery.ts
  src/schema/commentSchema.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#12 FE-50 ♻️ EmotionLog API 쿼리 키 팩토리 적용
  src/apis/queries.ts
  src/hooks/useEmotionLogQuery.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#6 FE-12 ✨ 글로벌 색상, 폰트 적용 및 기본적인 라우터 설정 머지 요청
  .gitignore
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/assets/ico_X.svg
  src/assets/ico_arrow_down.svg
  src/assets/ico_arrow_down_gray.svg
  src/assets/ico_arrow_left.svg
  src/assets/ico_arrow_right.svg
  src/assets/ico_arrow_up.svg
  src/assets/ico_camera.svg
  src/assets/ico_external_link.svg
  src/assets/ico_face_angry.svg
  src/assets/ico_face_heart.svg
  src/assets/ico_face_sad.svg
  src/assets/ico_face_smiling.svg
  src/assets/ico_face_thinking.svg
  src/assets/ico_like.svg
  src/assets/ico_logo.svg
  src/assets/ico_more_arrow_down.svg
  src/assets/ico_more_vertical.svg
  src/assets/ico_search.svg
  src/assets/ico_share.svg
  src/assets/ico_user.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/assets/img_magnifier.png
  src/assets/img_paraph.png
  src/assets/img_paraph_small.png
  src/assets/img_pr_emotions.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_examples.png
  src/assets/img_pr_graph.png
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/addepigram/index.tsx
  src/pages/epigrams/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/pages/signup/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Epic :rocket:

#13 FE-23 ✨ 로그인, 회원가입 페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/ico_logo.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/components/socialLogin/index.tsx
  src/index.css
  src/main.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#15 FE-52 :bug: : 오타 수정
  package-lock.json
  package.json
  src/apis/queries.ts
  src/apis/user.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#16 FE-49 ♻️ Epigram API 빌드 오류 수정 및 main 브랜치 최신화 충돌 해결
  .gitignore
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/common.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/assets/ico_X.svg
  src/assets/ico_arrow_down.svg
  src/assets/ico_arrow_down_gray.svg
  src/assets/ico_arrow_left.svg
  src/assets/ico_arrow_right.svg
  src/assets/ico_arrow_up.svg
  src/assets/ico_camera.svg
  src/assets/ico_external_link.svg
  src/assets/ico_face_angry.svg
  src/assets/ico_face_heart.svg
  src/assets/ico_face_sad.svg
  src/assets/ico_face_smiling.svg
  src/assets/ico_face_thinking.svg
  src/assets/ico_like.svg
  src/assets/ico_logo.svg
  src/assets/ico_more_arrow_down.svg
  src/assets/ico_more_vertical.svg
  src/assets/ico_search.svg
  src/assets/ico_share.svg
  src/assets/ico_user.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/assets/img_magnifier.png
  src/assets/img_paraph.png
  src/assets/img_paraph_small.png
  src/assets/img_pr_emotions.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_examples.png
  src/assets/img_pr_graph.png
  src/hooks/useDeleteEpigram.ts
  src/hooks/usePostEpigram.ts
  src/index.css
  src/main.tsx
  src/pages/addepigram/index.tsx
  src/pages/epigrams/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/pages/signup/index.tsx
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramPost.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Doc :memo:, Type: Refactor :recycle:

#17 FE-17 ✨ API 에픽 브랜치 메인에 머지 요청
  src/apis/auth.ts
  src/apis/comment.ts
  src/apis/common.ts
  src/apis/emotionLog.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/hooks/authQuery.ts
  src/hooks/useCommentQuery.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/hooks/useUserQuery.ts
  src/pages/.empty
  src/schema/authSchema.ts
  src/schema/commentSchema.ts
  src/schema/emotionLogSchema.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
Labels: Priority: High 🔥, Type: Epic :rocket:

#24 FE-25 ✨ 로그인, 회원가입 API 연동 및 토큰 저장
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/index.ts
  src/assets/.empty
  src/components/.empty
  src/hooks/authQuery.ts
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#22 FE-8 :sparkles: : 에피그램 리스트 카드 컴포넌트
  global.css
  src/apis/epigram/EpigramGet.ts
  src/assets/ico_plus.svg
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/ViewMore.tsx
  src/hooks/useGetEpigrams.ts
Labels: Priority: Medium :bookmark:

#21 FE-13 ✨ 모달 컴포넌트 작성 및 반응형 구현
  src/assets/.empty
  src/assets/ico_modal_alarm.svg
  src/components/.empty
  src/components/Modal/commentDeleteModal.tsx
  src/components/Modal/completeModal.tsx
  src/components/Modal/profileModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#27 FE-50 ♻️ EmotionLog API 관련 코드 리팩토링
  src/apis/emotionLog.ts
  src/hooks/useEmotionLogQuery.ts
  src/schema/emotionLogSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#25 FE-47 ✨ : 감정컴포넌트 css 작업
  src/components/EmotionList.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#29 FE-58 ✨ 검색페이지 UI 작업
  src/pages/search/RecentSearches.tsx
  src/pages/search/SearchCard.tsx
  src/pages/search/data.ts
  src/pages/search/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#31 FE-18 ✨ 헤더 컴포넌트 UI
  package-lock.json
  package.json
  src/App.tsx
  src/assets/ico_gnb_menu.svg
  src/components/Header.tsx
  src/laytout/Layout.tsx
  src/main.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#30 FE-13 ✨ 모달 컴포넌트 컨벤션 수정 및 데이터가 없을 때 디폴트 이미지 기능
  src/assets/ico_X.svg
  src/assets/ico_profile.svg
  src/components/FixedButton.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/components/Modal/completeModal.tsx
  src/components/Modal/profileModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#36 FE-65 ♻️ 전체적인 코드 수정이 들어간 로그인, 회원가입 페이지
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/main.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#26 FE-3 ✨ 로그인, 회원가입 페이지 구현 머지 요청
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/index.ts
  src/assets/.empty
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/components/.empty
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
Labels: Priority: High 🔥, Type: Epic :rocket:

#35 FE-48 ✨ 유저의 댓글 목록 조회 API 추가
  src/apis/queries.ts
  src/apis/user.ts
  src/hooks/useUserQuery.ts
  src/schema/userSchema.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#37 FE-4 🔀 : 공통컴포넌트 epic 최신화
  global.css
  package-lock.json
  package.json
  src/apis/auth.ts
  src/apis/index.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
Labels: Priority: High 🔥

#23 FE-49 ♻️ Epigram 스키마, API 요청, useQuery 수정
  src/apis/common.ts
  src/apis/epigram.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/queries.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
  src/schema/epigramSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#41 FE-1 🔀 랜딩 페이지 epic 브랜치 최신화
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/index.ts
  src/assets/.empty
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/components/.empty
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#32 FE-64 ✨ 에피그램 작성 버튼 & 스크롤 내릴 시 브라우저 상단으로 이동하는 버튼 제작
  src/assets/ico_plus.svg
  src/components/FixedButton.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#34 FE-22 ✨ 태그 컴포넌트
  src/components/HashTag.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#43 FE-1 ✨ 랜딩 페이지 구현_main에 머지 요청
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/assets/img_bg_bottom.png
  src/assets/img_bg_top.png
  src/assets/img_pr_emotions_medium.png
  src/assets/img_pr_epigram.png
  src/assets/img_pr_epigram_medium.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_graph_medium.png
  src/index.css
  src/pages/main/index.tsx
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:

#38 FE-18 ✨ 헤더 컴포넌트 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header/index.tsx
  src/index.css
  src/layout/Layout.tsx
Labels: Priority: Medium :bookmark:

#42 FE-47 ✨ 감정컴포넌트 API 연결
  package-lock.json
  package.json
  src/components/EmotionList.tsx
  src/hooks/useEmotionLogQuery.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#45 FE-56 🔀 검색페이지 epic 브랜치 최신화
  .github/PULL_REQUEST_TEMPLATE.md
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_bg_bottom.png
  src/assets/img_bg_top.png
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/assets/img_pr_emotions_medium.png
  src/assets/img_pr_epigram.png
  src/assets/img_pr_epigram_medium.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_graph_medium.png
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/index.css
  src/main.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#28 FE-52 ♻️ Comment API 관련 코드 리팩토링
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/assets/.empty
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/components/.empty
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/hooks/useCommentQuery.ts
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
  src/schema/commentSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#48 FE-67 ♻️ : 유저댓글 관련 GetUserCommentReponse을 댓글 ResponseSchema로 통일화
  src/apis/comment.ts
  src/apis/user.ts
  src/schema/commentSchema.ts
  src/schema/userSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#49 FE-49 ♻️ : Epigrams Comment 겹치는 부분 통일 수정 및 main.tsx에 에러 코드 추가
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/apis/comment.ts
  src/apis/epigram.ts
  src/apis/queries.ts
  src/assets/img_bg_bottom.png
  src/assets/img_bg_top.png
  src/assets/img_pr_emotions_medium.png
  src/assets/img_pr_epigram.png
  src/assets/img_pr_epigram_medium.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_graph_medium.png
  src/hooks/useCommentQuery.ts
  src/hooks/useEpigramQuery.ts
  src/index.css
  src/main.tsx
  src/schema/commentSchema.ts
  src/schema/epigramSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#50 FE-68 ♻️ 전체적인 API 수정 머지요청
  src/apis/comment.ts
  src/apis/common.ts
  src/apis/emotionLog.ts
  src/apis/epigram.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/hooks/useCommentQuery.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/hooks/useUserQuery.ts
  src/main.tsx
  src/schema/commentSchema.ts
  src/schema/emotionLogSchema.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
  src/schema/epigramSchema.ts
  src/schema/userSchema.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#52 FE-4 🔀 공통브랜치 epic 최신화
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/apis/comment.ts
  src/apis/common.ts
  src/apis/emotionLog.ts
  src/apis/epigram.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/assets/img_bg_bottom.png
  src/assets/img_bg_top.png
  src/assets/img_pr_emotions_medium.png
  src/assets/img_pr_epigram.png
  src/assets/img_pr_epigram_medium.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_graph_medium.png
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/hooks/useCommentQuery.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/main/index.tsx
  src/schema/commentSchema.ts
  src/schema/emotionLogSchema.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
  src/schema/epigramSchema.ts
  src/schema/userSchema.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#44 FE-59 ✨ 검색 페이지 API 연동
  src/apis/epigram.ts
  src/apis/queries.ts
  src/hooks/useEpigramQuery.ts
  src/pages/search/SearchCard.tsx
  src/pages/search/data.ts
  src/pages/search/index.tsx
  src/schema/epigramSchema.ts
  src/utils/.empty
  src/utils/hexConverter.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#55 FE-8 에피그램 리스트 카드 컴포넌트 리팩토링
  src/components/EpigramList.tsx
  src/hooks/useEpigramQuery.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#56 FE-3 🔀 : 로그인,회원가입 epic 최신화
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/apis/comment.ts
  src/apis/common.ts
  src/apis/emotionLog.ts
  src/apis/epigram.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/assets/img_bg_bottom.png
  src/assets/img_bg_top.png
  src/assets/img_pr_emotions_medium.png
  src/assets/img_pr_epigram.png
  src/assets/img_pr_epigram_medium.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_graph_medium.png
  src/hooks/useCommentQuery.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/main/index.tsx
  src/schema/commentSchema.ts
  src/schema/emotionLogSchema.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
  src/schema/epigramSchema.ts
  src/schema/userSchema.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#46 FE-6 ✨ 댓글 리스트 및 카드 컴포넌트
  package-lock.json
  package.json
  src/assets/ico_plus_blue.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/ViewMore.tsx
  src/hooks/useInfiniteQuery.ts
  src/utils/TimeFormatter.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#58 FE-4 :bug: 공통컴포넌트
  src/App.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#57 FE-4 🔀 공통컴포넌트 main에 머지 요청
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/epigram.ts
  src/assets/ico_X.svg
  src/assets/ico_gnb_menu.svg
  src/assets/ico_modal_alarm.svg
  src/assets/ico_plus.svg
  src/assets/ico_plus_blue.svg
  src/assets/ico_profile.svg
  src/assets/ico_user.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/FixedButton.tsx
  src/components/HashTag.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/components/Modal/completeModal.tsx
  src/components/Modal/profileModal.tsx
  src/components/ViewMore.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useInfiniteQuery.ts
  src/layout/Layout.tsx
  src/schema/epigramSchema.ts
  src/utils/TimeFormatter.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#60 FE-56 🔀 : 검색페이지 epic 최신화
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/comment.ts
  src/apis/common.ts
  src/apis/emotionLog.ts
  src/apis/epigram.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/assets/ico_X.svg
  src/assets/ico_gnb_menu.svg
  src/assets/ico_modal_alarm.svg
  src/assets/ico_plus.svg
  src/assets/ico_plus_blue.svg
  src/assets/ico_profile.svg
  src/assets/ico_user.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/FixedButton.tsx
  src/components/HashTag.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/components/Modal/completeModal.tsx
  src/components/Modal/profileModal.tsx
  src/components/ViewMore.tsx
  src/hooks/useCommentQuery.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/useInfiniteQuery.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/hooks/useUserQuery.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/schema/commentSchema.ts
  src/schema/emotionLogSchema.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
  src/schema/epigramSchema.ts
  src/schema/userSchema.ts
  src/utils/TimeFormatter.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#61 FE-69 🎨 검색페이지에서 사용하는 태그부분 공통 태그컴포넌트로 수정
  src/components/HashTag.tsx
  src/pages/search/RecentSearches.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#65 FE-14 🔀 에피그램 상세페이지 최신화
  .github/PULL_REQUEST_TEMPLATE.md
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/comment.ts
  src/apis/common.ts
  src/apis/emotionLog.ts
  src/apis/epigram.ts
  src/apis/epigram/EpigramDelete.ts
  src/apis/epigram/EpigramGet.ts
  src/apis/epigram/EpigramPatch.ts
  src/apis/epigram/EpigramPost.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/assets/.empty
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/img_bg_bottom.png
  src/assets/img_bg_top.png
  src/assets/img_logo_google.png
  src/assets/img_logo_kakao.png
  src/assets/img_logo_naver.png
  src/assets/img_pr_emotions_medium.png
  src/assets/img_pr_epigram.png
  src/assets/img_pr_epigram_medium.png
  src/assets/img_pr_epigrams.png
  src/assets/img_pr_graph_medium.png
  src/components/.empty
  src/components/socialLogin/index.tsx
  src/hooks/authQuery.ts
  src/hooks/useCommentQuery.ts
  src/hooks/useDeleteEpigram.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGetEpigrams.ts
  src/hooks/usePatchEpigram.ts
  src/hooks/usePostEpigram.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/pages/epigramDetail/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/authSchema.ts
  src/schema/commentSchema.ts
  src/schema/emotionLogSchema.ts
  src/schema/epigram/EpigramDelete.ts
  src/schema/epigram/EpigramGet.ts
  src/schema/epigram/EpigramPatch.ts
  src/schema/epigram/EpigramPost.ts
  src/schema/epigramSchema.ts
  src/schema/userSchema.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#67 FE-14 🔀 에피그램 상세페이지 최신화(다시)
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/epigram.ts
  src/assets/ico_X.svg
  src/assets/ico_gnb_menu.svg
  src/assets/ico_modal_alarm.svg
  src/assets/ico_plus.svg
  src/assets/ico_plus_blue.svg
  src/assets/ico_profile.svg
  src/assets/ico_user.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/FixedButton.tsx
  src/components/HashTag.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/components/Modal/completeModal.tsx
  src/components/Modal/profileModal.tsx
  src/components/ViewMore.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useInfiniteQuery.ts
  src/layout/Layout.tsx
  src/schema/epigramSchema.ts
  src/utils/TimeFormatter.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#68 FE-11 🔀 마이페이지 에픽 최신화
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/epigram.ts
  src/assets/ico_X.svg
  src/assets/ico_gnb_menu.svg
  src/assets/ico_modal_alarm.svg
  src/assets/ico_plus.svg
  src/assets/ico_plus_blue.svg
  src/assets/ico_profile.svg
  src/assets/ico_user.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/FixedButton.tsx
  src/components/HashTag.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/components/Modal/completeModal.tsx
  src/components/Modal/profileModal.tsx
  src/components/ViewMore.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useInfiniteQuery.ts
  src/layout/Layout.tsx
  src/schema/epigramSchema.ts
  src/utils/TimeFormatter.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#63 FE-56 ✨ 검색페이지 구현 main에 머지 요청
  package-lock.json
  src/components/HashTag.tsx
  src/pages/search/RecentSearches.tsx
  src/pages/search/SearchCard.tsx
  src/pages/search/index.tsx
  src/utils/.empty
  src/utils/hexConverter.ts
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:

#70 FE-73 :bug: : 랜딩페이지 이미지 경로 수정
  src/pages/main/index.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#66 FE-27 ✨ 에피그램페이지(메인페이지) 구현 완료
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/allEpigramList.tsx
  src/pages/epigrams/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Feature :sparkles:

#71 FE-10 🔀 에피그램(메인)페이지 최신화
  package-lock.json
  src/components/HashTag.tsx
  src/pages/main/index.tsx
  src/pages/search/RecentSearches.tsx
  src/pages/search/SearchCard.tsx
  src/pages/search/index.tsx
  src/utils/.empty
  src/utils/hexConverter.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#69 FE-72 ✨ 피드페이지
  src/App.tsx
  src/assets/ico_view_frames.svg
  src/assets/ico_view_line.svg
  src/components/EpigramCard.tsx
  src/pages/epigramboard/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#72 FE-10 ✨ 에피그램페이지 구현 main에 머지 요청
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/allEpigramList.tsx
  src/pages/epigrams/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Epic :rocket:

#64 FE-14 ✨ 에피그램 상세페이지
  global.css
  src/App.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/epigramdetail/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#59 FE-26 ✨ 카카오 로그인 구현
  .env
  src/App.tsx
  src/apis/postKakao.ts
  src/components/socialLogin/index.tsx
  src/constants/env.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useKakaoLogin.tsx
  src/pages/loginSocial/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#73 FE-74 🔀 소셜로그인 에픽 최신화
  .env
  src/App.tsx
  src/apis/postKakao.ts
  src/components/socialLogin/index.tsx
  src/constants/env.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useKakaoLogin.tsx
  src/pages/loginSocial/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#75 FE-14 ✨ 에피그램 상세페이지 UI 개선 및 기능 추가
  src/assets/ico_alert.svg
  src/assets/img_zigzag.png
  src/components/Modal/commentDeleteModal.tsx
  src/pages/epigramdetail/index.tsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#76 FE-14 🔀 에피그램 상세페이지 최신화
  package-lock.json
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/HashTag.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/allEpigramList.tsx
  src/pages/epigrams/index.tsx
  src/pages/main/index.tsx
  src/pages/search/RecentSearches.tsx
  src/pages/search/SearchCard.tsx
  src/pages/search/index.tsx
  src/utils/.empty
  src/utils/hexConverter.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#77 FE-14 🐛 tailwindconfig 파일 덧씌워짐 수정
  tailwind.config.js
Labels: Priority: High 🔥, Type: Bug :bug:

#78 FE-14 🔀 에피그램 상세페이지 메인에 merge 요청
  global.css
  src/App.tsx
  src/assets/ico_alert.svg
  src/assets/img_zigzag.png
  src/components/Modal/commentDeleteModal.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/epigramdetail/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Epic :rocket:

#79 FE-71 🔀 피드페이지 epic 메인 최신화
  global.css
  src/App.tsx
  src/assets/ico_alert.svg
  src/assets/img_zigzag.png
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramList.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/allEpigramList.tsx
  src/pages/epigrams/index.tsx
  src/pages/main/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#80 FE-71 🔀 피드페이지 main에 머지 요청
  src/App.tsx
  src/assets/ico_view_frames.svg
  src/assets/ico_view_line.svg
  src/components/EpigramCard.tsx
  src/pages/epigramboard/index.tsx
Labels: Priority: High 🔥, Type: Epic :rocket:

#81 FE-51 ✨ 구글 로그인 구현
  .env
  src/App.tsx
  src/apis/postGoogle.ts
  src/components/socialLogin/index.tsx
  src/constants/env.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useGoogleLogin.tsx
  src/pages/loginSocial/googlepage.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#82 FE-14 🐛 공통컴포넌트 미구현이었던 기능 추가
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderMiddle.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/index.tsx
  src/utils/timeFormatter.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#83 FE-70 ✨ 네이버 로그인 구현
  package-lock.json
  package.json
  src/App.tsx
  src/apis/postNaver.ts
  src/components/socialLogin/index.tsx
  src/constants/env.ts
  src/hooks/useNaverAuth.ts
  src/hooks/useNaverLogin.tsx
  src/pages/loginSocial/naverPage.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#84 FE-74 🔀 소셜로그인 epic 메인 최신화
  global.css
  src/App.tsx
  src/assets/ico_alert.svg
  src/assets/ico_view_frames.svg
  src/assets/ico_view_line.svg
  src/assets/img_zigzag.png
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderMiddle.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/epigramboard/index.tsx
  src/pages/epigramdetail/index.tsx
  src/utils/timeFormatter.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#86 FE-66 🔀 글 작성 페이지 최신화
  global.css
  package-lock.json
  src/App.tsx
  src/assets/ico_alert.svg
  src/assets/ico_view_frames.svg
  src/assets/ico_view_line.svg
  src/assets/img_zigzag.png
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/EpigramList.tsx
  src/components/HashTag.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderMiddle.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/epigramboard/index.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/allEpigramList.tsx
  src/pages/epigrams/index.tsx
  src/pages/main/index.tsx
  src/pages/search/RecentSearches.tsx
  src/pages/search/SearchCard.tsx
  src/pages/search/index.tsx
  src/utils/.empty
  src/utils/hexConverter.ts
  src/utils/timeFormatter.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#87 FE-11 🔀 마이페이지 epic 메인 최신화
  global.css
  package-lock.json
  src/App.tsx
  src/assets/ico_alert.svg
  src/assets/ico_view_frames.svg
  src/assets/ico_view_line.svg
  src/assets/img_zigzag.png
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/EpigramList.tsx
  src/components/HashTag.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderMiddle.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/index.tsx
  src/components/Modal/commentDeleteModal.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramDetail/index.tsx
  src/pages/epigramboard/index.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/allEpigramList.tsx
  src/pages/epigrams/index.tsx
  src/pages/main/index.tsx
  src/pages/search/RecentSearches.tsx
  src/pages/search/SearchCard.tsx
  src/pages/search/index.tsx
  src/utils/.empty
  src/utils/hexConverter.ts
  src/utils/timeFormatter.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#88 FE-39 ✨ 마이페이지 구현
  package-lock.json
  package.json
  src/apis/emotionLog.ts
  src/apis/queries.ts
  src/assets/ico_mypage_search.svg
  src/components/EmotionList.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/mypage/MyCommentsList.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/EmotionCalendar.tsx
  src/pages/mypage/emotionController/EmotionChart.tsx
  src/pages/mypage/emotionController/emotionData.ts
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
  src/schema/emotionLogSchema.ts
  src/schema/userSchema.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#89 FE-11 ✨ 마이페이지 메인에 merge 요청
  package-lock.json
  package.json
  src/apis/emotionLog.ts
  src/apis/queries.ts
  src/assets/ico_mypage_search.svg
  src/components/EmotionList.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/mypage/MyCommentsList.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/EmotionCalendar.tsx
  src/pages/mypage/emotionController/EmotionChart.tsx
  src/pages/mypage/emotionController/emotionData.ts
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
  src/schema/emotionLogSchema.ts
  src/schema/userSchema.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Epic :rocket:

#91 FE-80 💄 에피그램 상세페이지 UI 수정
  src/pages/epigramdetail/index.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#90 FE-78 ♻️ 알림메시지 refactor
  src/components/AlertMessage.tsx
  src/components/CommentList/CommentCard.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/main.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#92 FE-11 🔀 소셜로그인 epic 메인 최신화
  package-lock.json
  package.json
  src/apis/emotionLog.ts
  src/apis/queries.ts
  src/assets/ico_mypage_search.svg
  src/components/AlertMessage.tsx
  src/components/CommentList/CommentCard.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/MyCommentsList.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/EmotionCalendar.tsx
  src/pages/mypage/emotionController/EmotionChart.tsx
  src/pages/mypage/emotionController/emotionData.ts
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/emotionLogSchema.ts
  src/schema/userSchema.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#93 FE-74 ♻️ 소셜로그인 UI, 코드 관련해서 전체적으로 리펙토링
  src/App.tsx
  src/apis/postGoogle.ts
  src/apis/postKakao.ts
  src/apis/postNaver.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/components/socialLogin/index.tsx
  src/components/socialLogin/useGoogleLogin.tsx
  src/components/socialLogin/useKakaoLogin.tsx
  src/components/socialLogin/useNaverLogin.tsx
  src/constants/env.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useGoogleLogin.tsx
  src/hooks/useKakaoAuth.ts
  src/hooks/useKakaoLogin.tsx
  src/hooks/useNaverAuth.ts
  src/hooks/useNaverLogin.tsx
  src/pages/loginSocial/googlepage.tsx
  src/pages/loginSocial/index.tsx
  src/pages/loginSocial/naverPage.tsx
  src/pages/loginSocialloading/googlePage.tsx
  src/pages/loginSocialloading/kakaoPage.tsx
  src/pages/loginSocialloading/naverPage.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#94 FE-74 ✨ 소셜로그인 메인에 merge 요청
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/apis/postGoogle.ts
  src/apis/postKakao.ts
  src/apis/postNaver.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/components/socialLogin/index.tsx
  src/components/socialLogin/useGoogleLogin.tsx
  src/components/socialLogin/useKakaoLogin.tsx
  src/components/socialLogin/useNaverLogin.tsx
  src/constants/env.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/pages/loginSocialloading/googlePage.tsx
  src/pages/loginSocialloading/kakaoPage.tsx
  src/pages/loginSocialloading/naverPage.tsx
Labels: Priority: High 🔥, Type: Epic :rocket:

#95 FE-82 ♻️ local storage로 변경 및 소셜로그인 UI 수정
  package-lock.json
  package.json
  src/apis/index.ts
  src/components/EmotionList.tsx
  src/components/Header/index.tsx
  src/components/socialLogin/useGoogleLogin.tsx
  src/components/socialLogin/useKakaoLogin.tsx
  src/components/socialLogin/useNaverLogin.tsx
  src/hooks/authQuery.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/pages/loginSocialloading/googlePage.tsx
  src/pages/loginSocialloading/kakaoPage.tsx
  src/pages/loginSocialloading/naverPage.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#85 FE-66 ✨ 글 작성 페이지 완성
  src/pages/addepigram/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#97 FE-77 🔀 글 수정 페이지 에픽 최신화
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/apis/emotionLog.ts
  src/apis/index.ts
  src/apis/postGoogle.ts
  src/apis/postKakao.ts
  src/apis/postNaver.ts
  src/apis/queries.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/assets/ico_mypage_search.svg
  src/components/AlertMessage.tsx
  src/components/CommentList/CommentCard.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/HashTag.tsx
  src/components/Header/index.tsx
  src/components/socialLogin/index.tsx
  src/components/socialLogin/useGoogleLogin.tsx
  src/components/socialLogin/useKakaoLogin.tsx
  src/components/socialLogin/useNaverLogin.tsx
  src/constants/env.ts
  src/hooks/authQuery.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/hooks/useUserQuery.ts
  src/index.css
  src/main.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/login/index.tsx
  src/pages/loginSocialloading/googlePage.tsx
  src/pages/loginSocialloading/kakaoPage.tsx
  src/pages/loginSocialloading/naverPage.tsx
  src/pages/main/index.tsx
  src/pages/mypage/MyCommentsList.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/EmotionCalendar.tsx
  src/pages/mypage/emotionController/EmotionChart.tsx
  src/pages/mypage/emotionController/emotionData.ts
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/schema/emotionLogSchema.ts
  src/schema/userSchema.ts
  tailwind.config.js
Labels: Priority: High 🔥, Type: Merge :truck:

#99 FE-84 💄 공통컴포넌트 UI 수정
  src/assets/ico_bookmark_gray.svg
  src/assets/ico_bookmark_purple.svg
  src/assets/ico_bookmark_red.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/Header/index.tsx
  src/layout/Layout.tsx
  src/pages/epigrams/index.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/index.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#100 FE-79 🔀 UI 수정 브랜치 최신화
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/apis/postGoogle.ts
  src/apis/postKakao.ts
  src/apis/postNaver.ts
  src/assets/ico_logo_google.svg
  src/assets/ico_logo_kakao.svg
  src/assets/ico_logo_naver.svg
  src/components/AlertMessage.tsx
  src/components/CommentList/CommentCard.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/socialLogin/index.tsx
  src/components/socialLogin/useGoogleLogin.tsx
  src/components/socialLogin/useKakaoLogin.tsx
  src/components/socialLogin/useNaverLogin.tsx
  src/constants/env.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/main.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/login/index.tsx
  src/pages/loginSocialloading/googlePage.tsx
  src/pages/loginSocialloading/kakaoPage.tsx
  src/pages/loginSocialloading/naverPage.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#102 Fix 🐛 main 브랜치로 다시 배포하기
  src/App.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#103 FE-79 🔀 UI 브랜치 최신화
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/components/EmotionList.tsx
  src/components/Header/index.tsx
  src/components/socialLogin/useGoogleLogin.tsx
  src/components/socialLogin/useKakaoLogin.tsx
  src/components/socialLogin/useNaverLogin.tsx
  src/hooks/authQuery.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/pages/loginSocialloading/googlePage.tsx
  src/pages/loginSocialloading/kakaoPage.tsx
  src/pages/loginSocialloading/naverPage.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#104 FE-79 🔀 UI 브랜치 메인에 merge 요청
  src/assets/ico_bookmark_gray.svg
  src/assets/ico_bookmark_purple.svg
  src/assets/ico_bookmark_red.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/Header/index.tsx
  src/layout/Layout.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/index.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Epic :rocket:

#105 FE-86 ♻️ App 파일 수정 및 Error, Loaing 파일 추가
  package-lock.json
  package.json
  src/App.tsx
  src/assets/ico_sad.svg
  src/components/Error.tsx
  src/components/Loading.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#98 FE-77 ✨ 글 수정 페이지 구현
  src/pages/addepigram/index.tsx
  src/pages/editepigram/index.tsx
  src/schema/epigramSchema.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#106 FE-79 🔀 메인 및 에픽 최신화 merge 요청
  src/App.tsx
  src/assets/ico_bookmark_gray.svg
  src/assets/ico_bookmark_purple.svg
  src/assets/ico_bookmark_red.svg
  src/components/CommentList/CommentCard.tsx
  src/components/CommentList/index.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/Header/index.tsx
  src/layout/Layout.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/index.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/index.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#107 FE-5 🔀 글 작성 페이지 에픽 main에 머지 요청
  src/components/HashTag.tsx
  src/pages/addepigram/index.tsx
  src/pages/editepigram/index.tsx
  src/schema/epigramSchema.ts
Labels: Priority: High 🔥, Type: Epic :rocket:

#109 FE-87 ♻️ vercel.json 추가
  src/apis/index.ts
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/index.tsx
  src/components/ViewMore.tsx
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/pages/search/SearchCard.tsx
  tailwind.config.js
  vercel.json
Labels: Priority: High 🔥, Type: Refactor :recycle:

#108 FE-88 ♻️ 상세페이지 리팩토링
  src/components/ErrorComponent.tsx
  src/components/SuspenseWrapper.tsx
  src/hooks/useCommentQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useInfiniteQuery.ts
  src/hooks/useUserQuery.ts
  src/pages/epigramdetail/AddComment.tsx
  src/pages/epigramdetail/EpigramCommentList.tsx
  src/pages/epigramdetail/EpigramDetailMain.tsx
  src/pages/epigramdetail/index.tsx
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#110 FE-85 🔀 최적화 에픽 최신화
  src/apis/index.ts
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/index.tsx
  src/components/HashTag.tsx
  src/components/ViewMore.tsx
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/pages/addepigram/index.tsx
  src/pages/editepigram/index.tsx
  src/pages/search/SearchCard.tsx
  src/schema/epigramSchema.ts
  tailwind.config.js
  vercel.json
Labels: Priority: High 🔥, Type: Merge :truck:

#111 FE-89 ♻️ 에피그램페이지, 마이페이지 리팩토링
  src/apis/index.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/index.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#112 FE-91 ♻️ 상세페이지 및 피드페이지 최적화/ 랜딩페이지 애니메이션
  package-lock.json
  package.json
  src/components/CommentList/index.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/EpigramList.tsx
  src/components/ErrorComponent.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/index.tsx
  src/hooks/useEpigramQuery.ts
  src/hooks/useInfiniteQuery.ts
  src/pages/epigramdetail/AddComment.tsx
  src/pages/epigramdetail/EpigramCommentList.tsx
  src/pages/epigramdetail/EpigramDetailMain.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/MyCommentsList.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#115 FE-92 ♻️ 에피그램 작성 페이지 최적화
  src/pages/addepigram/index.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#116 FE-89 ♻️ 에피그램페이지, 마이페이지 필요없는 코드 삭제 및 디자인 추가
  src/apis/index.ts
  src/components/EmotionList.tsx
  src/components/EpigramList.tsx
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/pages/addepigram/index.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramdetail/EpigramDetailMain.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/login/index.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#118 FE-85 🐛 에피그램삭제 관련 오류 수정
  src/pages/epigramdetail/EpigramDetailMain.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#119 FE-89 ♻️ 에피그램페이지, 마이페이지 최적화 및 리펙토링
  global.css
  src/App.tsx
  src/components/EmotionList.tsx
  src/hooks/useEmotionLogQuery.ts
  src/pages/epigramdetail/EpigramDetailMain.tsx
  src/pages/epigrams/AlertEmotion.tsx
  src/pages/epigrams/index.tsx
  src/pages/mypage/MyCommentsList.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/index.tsx
  src/pages/notfound/index.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#120 FE-85 ♻️ 최적화 작업 및 리펙토링, 404페이지 제작
  global.css
  package-lock.json
  package.json
  src/App.tsx
  src/apis/index.ts
  src/assets/ico_sad.svg
  src/components/CommentList/index.tsx
  src/components/EmotionList.tsx
  src/components/EpigramCard/LikeButton.tsx
  src/components/EpigramCard/index.tsx
  src/components/EpigramList.tsx
  src/components/Error.tsx
  src/components/ErrorComponent.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderRight.tsx
  src/components/Header/index.tsx
  src/components/Loading.tsx
  src/components/SuspenseWrapper.tsx
  src/hooks/useCommentQuery.ts
  src/hooks/useEmotionLogQuery.ts
  src/hooks/useEpigramQuery.ts
  src/hooks/useGoogleAuth.ts
  src/hooks/useInfiniteQuery.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useNaverAuth.ts
  src/hooks/useUserQuery.ts
  src/pages/addepigram/index.tsx
  src/pages/editepigram/index.tsx
  src/pages/epigramdetail/AddComment.tsx
  src/pages/epigramdetail/EpigramCommentList.tsx
  src/pages/epigramdetail/EpigramDetailMain.tsx
  src/pages/epigramdetail/index.tsx
  src/pages/epigrams/AlertEmotion.tsx
  src/pages/epigrams/TodayEpigram.tsx
  src/pages/epigrams/allCommentList.tsx
  src/pages/epigrams/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/MyCommentsList.tsx
  src/pages/mypage/MyEpigramList.tsx
  src/pages/mypage/UserProfile.tsx
  src/pages/mypage/emotionController/index.tsx
  src/pages/mypage/index.tsx
  src/pages/notfound/index.tsx
  src/pages/search/index.tsx
  tailwind.config.js
Labels: Priority: High 🔥, Type: Refactor :recycle:

#121 FE-28 💄 새로운 로고 적용 및 자잘한 UI 수정
  src/assets/ico_newLogo.svg
  src/components/EmotionList.tsx
  src/components/Header/HeaderLeft.tsx
  src/components/Header/HeaderMiddle.tsx
  src/components/socialLogin/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/signup/index.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#122 📝 README.md 제작
  README.md
Labels: Priority: Medium :bookmark:, Type: Doc :memo:
